# Generated by Django 3.2 on 2022-09-30 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Audit Parameter Id')),
                ('parameter', models.CharField(max_length=200, verbose_name='Parameter Name')),
                ('audit_weightage', models.FloatField(default=1.0, null=True, verbose_name='Audit Weightage')),
                ('keyword', models.CharField(max_length=200, verbose_name='Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Channel Id')),
                ('url', models.URLField(verbose_name='Channel Url')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Channel Type Id')),
                ('channel_type', models.CharField(choices=[('social_media', 'Social Media'), ('owned_press_release', 'Owned Press Release'), ('company_website', 'Company Website')], max_length=50, unique=True, verbose_name='Channel Type')),
                ('channel_type_weightage', models.FloatField(default=1.0, null=True, verbose_name='Weightage')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Company Id')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Company Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('compliance_score', models.FloatField(default=0, verbose_name='Compliance Score')),
                ('previous_compliance_score', models.FloatField(default=0, verbose_name='Compliance Score')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Company Id')),
                ('start_Date', models.DateTimeField(auto_now_add=True)),
                ('end_Date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('type', models.CharField(choices=[('branding', 'branding'), ('positioning', 'positioning'), ('both', 'both')], max_length=70)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='MessageArchitecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='MA Id')),
                ('parameter', models.CharField(max_length=200, verbose_name='Parameter Name')),
                ('keyword', models.CharField(max_length=200, verbose_name='Keyword')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.engagement')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelTypeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.auditparameter')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.channeltype')),
            ],
        ),
        migrations.AddField(
            model_name='channeltype',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_details', to='configuration.engagement'),
        ),
        migrations.CreateModel(
            name='ChannelSourceParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('channel', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.channel', verbose_name='Channel Url')),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.auditparameter')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='configuration.channel')),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.auditparameter')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=70, verbose_name='Channel Name')),
                ('channel_type_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.channeltype')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.channelname'),
        ),
        migrations.AddField(
            model_name='channel',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.engagement'),
        ),
        migrations.AddField(
            model_name='channel',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.channeltype'),
        ),
        migrations.AddField(
            model_name='auditparameter',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.engagement', verbose_name='Engagement Details'),
        ),
    ]
