# Generated by Django 4.1.1 on 2022-09-29 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Channel Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Channel Type"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Company Id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Company Name"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "compliance_score",
                    models.FloatField(default=0, verbose_name="Compliance Score"),
                ),
                (
                    "previous_compliance_score",
                    models.FloatField(default=0, verbose_name="Compliance Score"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DNAElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dna_type",
                    models.CharField(max_length=10, null=True, verbose_name="DNA Type"),
                ),
                ("keywords", models.TextField(null=True, verbose_name="Keywords")),
            ],
        ),
        migrations.CreateModel(
            name="EngagementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engagement_name",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Engagement Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParameterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter_name",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Parameter Name"
                    ),
                ),
                (
                    "engagement_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration.engagementtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageArchitecture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="MA Id",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration.companydetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Measure Id",
                    ),
                ),
                (
                    "value",
                    models.TextField(max_length=1000, null=True, verbose_name="Value"),
                ),
                (
                    "weightage",
                    models.FloatField(default=1.0, null=True, verbose_name="Weightage"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "message_architecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measure_field",
                        to="configuration.messagearchitecture",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration.parametertype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Company Id",
                    ),
                ),
                ("start_Date", models.DateTimeField(auto_now_add=True)),
                ("end_Date", models.DateTimeField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration.companydetails",
                    ),
                ),
                (
                    "engagement_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration.engagementtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelTypeParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                (
                    "parameters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration.parametertype",
                    ),
                ),
                (
                    "type_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration.channeltype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelSourceParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                (
                    "parameters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration.parametertype",
                    ),
                ),
                (
                    "url",
                    models.ForeignKey(
                        max_length=200,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration.channel",
                        verbose_name="Channel Url",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Channel Id",
                    ),
                ),
                (
                    "url",
                    models.URLField(null=True, unique=True, verbose_name="Channel Url"),
                ),
                (
                    "weightage",
                    models.FloatField(default=1.0, null=True, verbose_name="Weightage"),
                ),
                (
                    "compliance_score",
                    models.FloatField(default=0, verbose_name="Compliance Score"),
                ),
                (
                    "previous_compliance_score",
                    models.FloatField(
                        default=0, verbose_name="Previous Compliance Score"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration.companydetails",
                    ),
                ),
                (
                    "type_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration.channeltype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel",
                        to="configuration.channel",
                    ),
                ),
                (
                    "parameters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration.parametertype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="channel",
            name="type_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="configuration.channeltype",
            ),
        ),
        migrations.CreateModel(
            name="ChannelTypeWeightage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weightage",
                    models.FloatField(default=1.0, null=True, verbose_name="Weightage"),
                ),
                (
                    "channel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_type",
                        to="configuration.channeltype",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_type_weightage",
                        to="configuration.companydetails",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "channel_type")},
            },
        ),
    ]
