# Generated by Django 4.1.1 on 2022-09-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DNAElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dna_type",
                    models.CharField(max_length=10, null=True, verbose_name="DNA Type"),
                ),
                ("keywords", models.TextField(null=True, verbose_name="Keywords")),
            ],
        ),
    ]
