# Generated by Django 4.1 on 2022-09-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='Engagement',
            new_name='engagement',
        ),
        migrations.AddField(
            model_name='engagement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
