# Generated by Django 4.1.1 on 2022-09-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelParameterWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameters",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="Parameters"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel",
                        to="configuration.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelSourceParameterWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameters",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="Parameters"
                    ),
                ),
                (
                    "url",
                    models.ForeignKey(
                        max_length=200,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration.channel",
                        verbose_name="Channel Url",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelTypeParameterWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameters",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="Parameters"
                    ),
                ),
                (
                    "type_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration.channeltype",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="channelsourceparameter",
            name="parameters",
        ),
        migrations.RemoveField(
            model_name="channelsourceparameter",
            name="url",
        ),
        migrations.RemoveField(
            model_name="channeltypeparameter",
            name="parameters",
        ),
        migrations.RemoveField(
            model_name="channeltypeparameter",
            name="type_name",
        ),
        migrations.AddField(
            model_name="channelsource",
            name="channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="configuration.channel",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="start_Date",
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name="ChannelParameter",
        ),
        migrations.DeleteModel(
            name="ChannelSourceParameter",
        ),
        migrations.DeleteModel(
            name="ChannelTypeParameter",
        ),
    ]
