# Generated by Django 3.2 on 2022-09-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='compliance_score',
            field=models.FloatField(default=0, verbose_name='Compliance Score'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='previous_compliance_score',
            field=models.FloatField(default=0, verbose_name='Compliance Score'),
        ),
    ]
