# Generated by Django 4.1 on 2022-09-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_rename_engagement_channel_engagement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelparameter',
            unique_together={('channel', 'parameters')},
        ),
        migrations.AlterUniqueTogether(
            name='channelsourceparameter',
            unique_together={('url', 'parameters')},
        ),
        migrations.AlterUniqueTogether(
            name='channeltypeparameter',
            unique_together={('type_name', 'parameters')},
        ),
        migrations.AlterUniqueTogether(
            name='engagement',
            unique_together={('type', 'company')},
        ),
    ]
