# Generated by Django 3.2 on 2022-09-30 18:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20220930_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.engagement'),
        ),
        migrations.AlterField(
            model_name='channelname',
            name='channel_type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.channeltype'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Engagement Id'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='start_Date',
            field=models.DateTimeField(),
        ),
    ]
