# Generated by Django 4.1 on 2022-10-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_channelparameter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_title',
            field=models.CharField(max_length=200, null=True, verbose_name='channel_Title'),
        ),
        migrations.AlterField(
            model_name='channeltype',
            name='channel_type',
            field=models.CharField(choices=[('social_media', 'Social Media'), ('owned_press_release', 'Owned Press Release'), ('company_website', 'Company Website')], max_length=50, verbose_name='Channel Type'),
        ),
    ]
