# Generated by Django 3.2 on 2022-09-30 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20220930_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditparameter',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.engagement', verbose_name='Engagement Details'),
        ),
    ]
