# Generated by Django 3.2 on 2022-09-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_auditparameter_engagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelparameter',
            name='parameters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.auditparameter'),
        ),
        migrations.AlterField(
            model_name='channelsourceparameter',
            name='channel',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='configuration.channel', verbose_name='Channel Url'),
        ),
        migrations.AlterField(
            model_name='channelsourceparameter',
            name='parameters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.auditparameter'),
        ),
    ]
