# Generated by Django 4.1 on 2022-10-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_channel_channel_title_alter_channeltype_channel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelsourceparameter',
            old_name='url',
            new_name='channel',
        ),
        migrations.AddField(
            model_name='engagement',
            name='compliance_score',
            field=models.FloatField(default=0, verbose_name='Compliance Score'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='previous_compliance_score',
            field=models.FloatField(default=0, verbose_name='Compliance Score'),
        ),
        migrations.AlterUniqueTogether(
            name='channelsourceparameter',
            unique_together={('channel', 'parameters')},
        ),
    ]
