# Generated by Django 4.1 on 2022-10-03 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_rename_url_channelsourceparameter_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='compliance_score',
            field=models.FloatField(default=0, verbose_name='Present Compliance Score'),
        ),
        migrations.AddField(
            model_name='channel',
            name='previous_compliance_score',
            field=models.FloatField(default=-1, verbose_name='Previous Compliance Score'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='compliance_score',
            field=models.FloatField(default=0, verbose_name='Present Compliance Score'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='previous_compliance_score',
            field=models.FloatField(default=-1, verbose_name='Previous Compliance Score'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='compliance_score',
            field=models.FloatField(default=0, verbose_name='Present Compliance Score'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='end_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='previous_compliance_score',
            field=models.FloatField(default=-1, verbose_name='Previous Compliance Score'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='start_Date',
            field=models.DateField(auto_now_add=True, verbose_name='Start Date'),
        ),
    ]
