# Generated by Django 4.1 on 2022-10-03 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_clienttype_channel_compliance_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='client_type',
            field=models.ForeignKey(default='d6181a6b-9443-4f1f-b95f-4ff2c4923c75', on_delete=django.db.models.deletion.PROTECT, to='configuration.clienttype'),
            preserve_default=False,
        ),
    ]
