# Generated by Django 3.2.14 on 2022-10-01 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_alter_channelsourceparameter_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_title',
            field=models.CharField(max_length=200, null=True, verbose_name='channel_Title'),
        ),
        migrations.AlterField(
            model_name='auditparameter',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.engagement', verbose_name='Engagement Details'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.engagement'),
        ),
        migrations.AlterField(
            model_name='channelname',
            name='channel_type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.channeltype'),
        ),
        migrations.AlterField(
            model_name='channelparameter',
            name='parameters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.auditparameter'),
        ),
        migrations.AlterField(
            model_name='channelsourceparameter',
            name='channel',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.channel', verbose_name='Channel Url'),
        ),
        migrations.AlterField(
            model_name='channelsourceparameter',
            name='parameters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.auditparameter'),
        ),
        migrations.AlterField(
            model_name='channeltype',
            name='channel_type',
            field=models.CharField(choices=[('social_media', 'Social Media'), ('owned_press_release', 'Owned Press Release'), ('company_website', 'Company Website')], max_length=50, verbose_name='Channel Type'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Company Id'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='start_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='channelparameter',
            unique_together={('channel', 'parameters')},
        ),
        migrations.AlterUniqueTogether(
            name='channelsourceparameter',
            unique_together={('channel', 'parameters')},
        ),
        migrations.AlterUniqueTogether(
            name='channeltypeparameter',
            unique_together={('type_name', 'parameters')},
        ),
        migrations.AlterUniqueTogether(
            name='engagement',
            unique_together={('type', 'company')},
        ),
    ]
