# Generated by Django 4.1 on 2022-10-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0008_clienttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="client_type",
            field=models.ForeignKey(
                default="4114c763-f1fa-4278-80c3-4432b969149e",
                on_delete=django.db.models.deletion.PROTECT,
                to="configuration.clienttype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clienttype",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
