# Generated by Django 4.1 on 2022-10-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0009_engagement_client_type_alter_clienttype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagement",
            name="end_Date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="start_Date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
