# Generated by Django 4.1 on 2022-10-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0010_alter_engagement_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
