# Generated by Django 4.1 on 2022-10-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0011_engagement_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="compliance_score",
            field=models.FloatField(default=0, verbose_name="Present Compliance Score"),
        ),
        migrations.AddField(
            model_name="channel",
            name="previous_compliance_score",
            field=models.FloatField(
                default=0, verbose_name="Previous Compliance Score"
            ),
        ),
        migrations.AlterField(
            model_name="companydetails",
            name="compliance_score",
            field=models.FloatField(default=0, verbose_name="Present Compliance Score"),
        ),
        migrations.AlterField(
            model_name="companydetails",
            name="previous_compliance_score",
            field=models.FloatField(
                default=0, verbose_name="Previous Compliance Score"
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="compliance_score",
            field=models.FloatField(default=0, verbose_name="Present Compliance Score"),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="previous_compliance_score",
            field=models.FloatField(
                default=0, verbose_name="Previous Compliance Score"
            ),
        ),
    ]
