# Generated by Django 4.1.1 on 2022-09-27 10:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Score Id",
                    ),
                ),
                (
                    "dna_alignment",
                    models.FloatField(default=0.0, verbose_name="DNA Alignment"),
                ),
                ("posmo_tag", models.FloatField(default=0.0, verbose_name="Posmo Tag")),
                (
                    "differentiator",
                    models.FloatField(default=0.0, verbose_name="Differentiator"),
                ),
                (
                    "value_proposition",
                    models.FloatField(default=0.0, verbose_name="Value Proposition"),
                ),
                ("tagline", models.FloatField(default=0.0, verbose_name="Tagline")),
                (
                    "total_score",
                    models.FloatField(default=0.0, verbose_name="Total Score"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_management.channeldata",
                    ),
                ),
            ],
        ),
    ]
