# Generated by Django 4.1.1 on 2022-09-29 09:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuration", "0002_channelparameterweights_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceParameterScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Source Parameter Id",
                    ),
                ),
                (
                    "parameters",
                    models.CharField(max_length=2000, verbose_name="Source Parameters"),
                ),
                (
                    "scource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter",
                        to="configuration.channelsource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelTypeParameterScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ChannelType Parameter Id",
                    ),
                ),
                (
                    "parameters",
                    models.CharField(
                        max_length=2000, verbose_name="ChannelType Parameters"
                    ),
                ),
                (
                    "channel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter",
                        to="configuration.channeltype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelParameterScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Channel Parameter Id",
                    ),
                ),
                (
                    "parameters",
                    models.CharField(
                        max_length=2000, verbose_name="Channel Parameters"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter",
                        to="configuration.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "overall_compliance_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Overall Compliance Score",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_info",
                        to="configuration.companydetails",
                    ),
                ),
            ],
        ),
    ]
