# Generated by Django 3.2 on 2022-09-30 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('audit_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditinformation',
            name='engagagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_info', to='configuration.channelname'),
        ),
    ]
