# Generated by Django 3.2 on 2022-09-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_engine', '0002_alter_auditinformation_engagagement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditinformation',
            old_name='engagagement',
            new_name='channel_name',
        ),
    ]
