# Generated by Django 3.2 on 2022-09-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_engine', '0003_rename_engagagement_auditinformation_channel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditInformation',
        ),
    ]
