# Generated by Django 3.2 on 2022-10-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_engine', '0004_delete_auditinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelparameterscore',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='channeltypeparameterscore',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='sourceparameterscore',
            name='parametersScores',
        ),
        migrations.AddField(
            model_name='channelparameterscore',
            name='parameter_score',
            field=models.FloatField(default=0.0, verbose_name='Parameter scores'),
        ),
        migrations.AddField(
            model_name='channeltypeparameterscore',
            name='parameter_score',
            field=models.FloatField(default=0.0, verbose_name='Parameter Score'),
        ),
        migrations.AddField(
            model_name='sourceparameterscore',
            name='parameter_score',
            field=models.FloatField(default=0.0, verbose_name='Parameter Score'),
        ),
    ]
