# Generated by Django 3.2 on 2022-10-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_engine', '0005_auto_20221001_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceparameterscore',
            old_name='scource',
            new_name='source',
        ),
    ]
