# Generated by Django 3.2 on 2022-10-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_engine', '0006_rename_scource_sourceparameterscore_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceparameterscore',
            name='matched_keyword_count',
            field=models.IntegerField(default=0, verbose_name='Mapped Keyword Count'),
        ),
    ]
