# Generated by Django 4.1 on 2022-10-02 05:08

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("audit_engine", "0007_sourceparameterscore_matched_keyword_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sourceparameterscore",
            old_name="matched_keyword_count",
            new_name="keyword_count",
        ),
        migrations.AddField(
            model_name="sourceparameterscore",
            name="keyword_frequencies",
            field=jsonfield.fields.JSONField(default="[]"),
        ),
    ]
