# Generated by Django 3.2 on 2022-10-01 06:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('audit_engine', '0007_sourceparameterscore_matched_keyword_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceparameterscore',
            old_name='matched_keyword_count',
            new_name='keyword_count',
        ),
        migrations.AddField(
            model_name='sourceparameterscore',
            name='keyword_frequencies',
            field=jsonfield.fields.JSONField(default='[]'),
        ),
    ]
