# Generated by Django 4.1 on 2022-10-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0012_channel_compliance_score_and_more"),
        (
            "audit_engine",
            "0008_rename_matched_keyword_count_sourceparameterscore_keyword_count_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourceparameterscore",
            name="keyword_count",
        ),
        migrations.RemoveField(
            model_name="sourceparameterscore",
            name="keyword_frequencies",
        ),
        migrations.AlterField(
            model_name="channelparameterscore",
            name="channel",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameter",
                to="configuration.channelparameter",
            ),
        ),
        migrations.AlterField(
            model_name="channelparameterscore",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="channeltypeparameterscore",
            name="channel_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameter",
                to="configuration.channeltypeparameter",
            ),
        ),
        migrations.AlterField(
            model_name="channeltypeparameterscore",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sourceparameterscore",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sourceparameterscore",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameter",
                to="configuration.channelsourceparameter",
            ),
        ),
    ]
