# Generated by Django 3.2 on 2022-09-30 04:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Data Id')),
                ('scraped_data', models.TextField(null=True, verbose_name='Scarped Data')),
                ('processed_data', models.TextField(blank=True, null=True, verbose_name='Processed Data')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.channel')),
            ],
        ),
    ]
