# Generated by Django 4.1.1 on 2022-09-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("audit_engine", "0001_initial"),
        ("content_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="scores",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="channel",
                to="audit_engine.scorecardparameter",
            ),
        ),
        migrations.AlterField(
            model_name="channeldata",
            name="scores",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="channel_data",
                to="audit_engine.scorecardparameter",
            ),
        ),
    ]
