# Generated by Django 3.2 on 2022-09-30 16:57

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20220930_1413'),
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Content Title', max_length=200, unique=True, verbose_name='Title')),
                ('number_of_words', models.IntegerField(default=0, verbose_name='Number Of Words')),
                ('main_content', models.TextField(verbose_name='Main Content')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFetchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('processed_words', models.TextField(verbose_name='Processed Words')),
                ('mapped_keywords_count', models.IntegerField(null=True, verbose_name='No. of Mapped Words')),
                ('unmapped_keywords_count', models.IntegerField(null=True, verbose_name='No. of Unmapped Words')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.channel')),
            ],
        ),
        migrations.CreateModel(
            name='MappedKeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapped_keywords', jsonfield.fields.JSONField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.channel')),
            ],
        ),
        migrations.CreateModel(
            name='UnmappedKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unmapped_keywords', models.TextField(null=True, verbose_name='Unmapped Keywords')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.channel')),
            ],
        ),
        migrations.DeleteModel(
            name='ChannelData',
        ),
    ]
