# Generated by Django 4.1 on 2022-10-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0002_auto_20220930_2227"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentfetchinfo",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="mappedkeywords",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="unmappedkeywords",
            name="channel",
        ),
        migrations.DeleteModel(
            name="Content",
        ),
        migrations.DeleteModel(
            name="ContentFetchInfo",
        ),
        migrations.DeleteModel(
            name="MappedKeyWords",
        ),
        migrations.DeleteModel(
            name="UnmappedKeywords",
        ),
    ]
